#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
#inhibit_all_warnings!

platform :ios, '10.0'

target 'Example_ModuleManager' do
  pod 'NNModule-swift', :path => '../'
  pod 'ModuleServices', :path => '../Modules/ModuleServices'
  pod 'LoginModule', :path => '../Modules/LoginModule'
  pod 'AModule', :path => '../Modules/AModule'
  pod 'BModule', :path => '../Modules/BModule'
  pod 'CModule', :path => '../Modules/CModule'
  pod 'ApplicationModule', :path => '../Modules/ApplicationModule'
  pod 'ConfigModule', :path => '../Modules/ConfigModule'
  pod 'TabBarController', :path => '../Modules/TabBarController'
  pod 'BaseModule', :path => '../Modules/BaseModule'
  pod 'SnapKit'
  pod 'ESTabBarController-swift'
  pod 'HandyJSON'
  pod 'MBProgressHUD'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.symbol_type == :bundle
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end

