#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
#inhibit_all_warnings!

platform :ios, '10.0'

target 'Example_ModuleManager' do
  pod 'NNModule-swift', :path => '../'
  pod 'ModuleServices', :path => '../Modules/ModuleServices'
  pod 'LoginModule', :path => '../Modules/LoginModule'
  pod 'AModule', :path => '../Modules/AModule'
  pod 'BModule', :path => '../Modules/BModule'
  pod 'CModule', :path => '../Modules/CModule'
  pod 'ApplicationModule', :path => '../Modules/ApplicationModule'
  pod 'TabBarController', :path => '../Modules/TabBarController'
  pod 'BaseModule', :path => '../Modules/BaseModule'
  pod 'SnapKit'
  pod 'ESTabBarController-swift'
  
end
